(function(w){
 'use strict';
 const busy=new Set(),tabs=new Map(),$=id=>document.getElementById(id),isHost=()=>state.room?.host_id===state.playerId;
 async function rpc(name,args){const {data,error}=await supabaseClient.rpc(name,args);if(error)throw Error(error.message);return data;}
 const action=(name,data={})=>rpc('alive_action',{p_code:state.currentRoomCode,p_action:name,p_data:data});
 function notice(text,error=false){let el=$('aliveNotice');if(!el){el=document.createElement('div');el.id='aliveNotice';el.setAttribute('role','status');document.body.append(el);}el.className=error?'notice error':'notice';el.textContent=text;el.hidden=false;clearTimeout(el._timer);el._timer=setTimeout(()=>el.hidden=true,error?15000:8000);}
 async function run(key,fn){if(busy.has(key))return;busy.add(key);try{return await fn();}catch(e){notice(e.message||'Действие не выполнено',true);}finally{busy.delete(key);}}
 async function refresh(){if(!state.currentRoomCode)return;const [room,players]=await Promise.all([dbFetchRoom(state.currentRoomCode),dbFetchPlayers(state.currentRoomCode)]);if(!room)throw Error('Комната недоступна');state.room=room;state.players=players;refreshControls();}
 function refreshControls(){if($('hostPhaseControls')&&!$('hostPhaseControls').contains(document.activeElement))$('hostPhaseControls').outerHTML=renderHostPhaseControls(state.room);syncGamePhaseTimerTicker();}
 function number(id,min,max){const el=$(id),n=Number(el?.value);if(!el||el.value.trim()===''||!Number.isInteger(n)||n<min||n>max)throw Error(`Введите целое число от ${min} до ${max}`);return n;}
 w.readGameNumber=number;
 w.canRevealCategory=(cards,room,category)=>{
  if(category==='goal')return {ok:false,reason:'Личная цель доступна только вам'};
  if(category==='special_condition')return {ok:true};
  if(room.current_phase==='awaiting_verdict')return {ok:!!room.final_reveal_unlocked,reason:'Ведущий пока не разрешил раскрытие'};
  const slots=room.settings?.round_reveals?.[(room.current_round||1)-1]||['any'];
  const opened=cards.filter(c=>c.revealed&&c.round_revealed===room.current_round&&!['goal','special_condition'].includes(c.category));
  const required=c=>slots.filter(x=>x===c).length,counts={};for(const c of opened)counts[c.category]=(counts[c.category]||0)+1;
  const wildUsed=Object.entries(counts).reduce((n,[c,count])=>n+Math.max(0,count-required(c)),0);
  const ok=opened.length<slots.length&&((counts[category]||0)<required(category)||wildUsed<slots.filter(x=>x==='any').length);
  return {ok,reason:ok?'':'Нет свободного раскрытия для этой категории'};
 };
 async function boot(){try{if(!supabaseClient)throw Error('Не удалось подключить базу');let {data,error}=await supabaseClient.auth.getSession();if(error)throw error;if(!data.session){({data,error}=await supabaseClient.auth.signInAnonymously());if(error)throw error;}const uid=data.session.user.id;if(state.playerId!==uid){saveRoomCode(null);state.playerId=uid;localStorage.setItem('playerId',uid);}await init();}catch(e){$('app').innerHTML='<h1>ОСТАТЬСЯ <span>В ЖИВЫХ</span></h1><div class="panel"><h2>Не удалось войти</h2><p>'+escapeHtml(e.message)+'</p><button class="btn btn-primary" onclick="location.reload()">Повторить</button></div>';}}
 w.AliveGame={rpc,action,refresh,notice,run,boot};
 w.dbUpdateRoom=async(code,patch)=>{if(!isHost())throw Error('Это действие доступно ведущему');if(patch.settings){const s=patch.settings;if(s.min_players>s.max_players)throw Error('Минимум участников больше максимума');if(s.rounds<1||s.rounds>50)throw Error('Число раундов: от 1 до 50');}let q=supabaseClient.from('rooms').update(patch).eq('code',code);if(state.room?.revision!=null)q=q.eq('revision',state.room.revision);const {data,error}=await q.select('*').maybeSingle();if(error)throw error;if(!data)throw Error('Состояние изменилось. Обновите экран и повторите');state.room=data;refreshControls();};
 w.generateCardsForRoom=w.assignPresetCardsForRoom=code=>rpc('alive_generate',{p_code:code});
 w.dbFetchHostNotes=async()=>{const rows=await action('host_notes'),properties={};let scenarioNotes='';for(const r of rows||[]){properties[r.bunker_property_id]=r.host_note;if(r.scenario_host_notes)scenarioNotes=r.scenario_host_notes;}return {properties,scenarioNotes};};
 w.dbSyncRoomBunkerProperties=async(code,scenario)=>{if(scenario)await rpc('alive_host_maintenance',{p_code:code,p_action:'sync_bunker'});};
 w.dbCleanupRoundBunkerEffects=async()=>{if(isHost())await rpc('alive_host_maintenance',{p_code:state.currentRoomCode,p_action:'cleanup'});};
 w.hostRevealRandomBonusProperty=async()=>{const result=await action('reveal_bonus');if(result.delayed)throw Error('Раскрытие отложено спецусловием. Следующая попытка будет доступна.');await refreshRoomBunkerProperties();return result.text||null;};
 w.actionRevealBonus=()=>run('bonus',async()=>{const text=await hostRevealRandomBonusProperty();if(!text){notice('Нет доступных закрытых свойств');return;}refreshBunkerList();await loadHostMasterPanel();});
 w.dbKickPlayer=(code,target)=>rpc('alive_moderate',{p_code:code,p_target:target,p_action:'kick'});
 w.dbSetMute=(code,target,actor,muted)=>rpc('alive_moderate',{p_code:code,p_target:target,p_action:muted?'mute':'unmute'});
 w.dbTimeoutPlayer=(code,target,actor,seconds)=>rpc('alive_moderate',{p_code:code,p_target:target,p_action:seconds>0?'timeout':'untimeout',p_seconds:seconds});
 w.dbSendChat=(code,text)=>rpc('alive_action',{p_code:code,p_action:'chat',p_data:{text}});
 w.dbSendPrivateChat=(code,sender,recipient,text)=>rpc('alive_action',{p_code:code,p_action:'chat',p_data:{text,target:recipient||null}});
 w.actionNominate=target=>run('nominate',async()=>{await action('nominate',{target});await refresh();await updateGameDynamic();});
 w.actionCastVote=target=>run('vote',async()=>{await action('vote',{target});state.myVoteThisRound=target;await refresh();await updateGameDynamic();});
 w.actionRevealTrait=id=>run('reveal',async()=>{await action('reveal',{card_id:Number(id)});await refresh();await loadMyCard();await updateGameDynamic();});
 w.resolveVoting=()=>rpc('alive_resolve_vote',{p_code:state.currentRoomCode});
 w.loadVoteProgress=async()=>{if(!$('voteProgress'))return;const p=await action('vote_progress');if($('voteProgress'))$('voteProgress').textContent=`Проголосовало: ${p.count} из ${p.total}`;};
 w.actionStartGame=()=>run('start',async()=>{await refresh();if(!isHost())throw Error('Только ведущий');if(state.room.phase!=='lobby')throw Error('Старт уже запущен');const ps=state.players.filter(p=>p.id!==state.room.host_id),min=state.room.settings?.min_players??2;if(ps.length<min)throw Error(`Нужно минимум ${min} игроков, ведущий не учитывается`);const unready=ps.find(p=>!p.is_ready);if(unready)throw Error(`${unready.name} ещё не готов(а)`);if(!state.room.scenario_id)throw Error('Выберите сценарий');state.room=await rpc('alive_start',{p_code:state.currentRoomCode});});
 w.cancelGameStart=()=>run('start',()=>dbUpdateRoom(state.currentRoomCode,{phase:'lobby',countdown_ends_at:null}));
 w.renderHostPhaseControls=room=>{if(!isHost()||room.current_phase==='finished')return '';const sec=room.settings?.phase_seconds?.[room.current_phase]??(phaseDuration(room.current_phase)||60),kind=room.phase_running?'pause':room.phase_paused_remaining>0?'resume':'start';return `<div id="hostPhaseControls" class="phase-controls"><button class="btn btn-primary btn-sm" onclick="AliveGame.timer('${kind}')">${{pause:'Пауза',resume:'Продолжить',start:'Старт'}[kind]}</button><button class="btn btn-ghost btn-sm" onclick="AliveGame.timer('reset')">Сброс</button><button class="btn btn-ghost btn-sm" onclick="AliveGame.timer('adjust',-15)">−15 с</button><button class="btn btn-ghost btn-sm" onclick="AliveGame.timer('adjust',30)">+30 с</button><label>Сек. <input id="phaseSeconds" type="number" min="0" max="86400" value="${sec}" aria-label="Длительность таймера"></label><button class="btn btn-ghost btn-sm" onclick="AliveGame.timer('start')">Задать</button><button class="btn btn-danger btn-sm" onclick="hostAdvancePhase()">Далее →</button></div>`;};
 AliveGame.timer=(kind,seconds)=>run('phase',async()=>{const n=seconds??(kind==='start'?number('phaseSeconds',0,86400):0);await refresh();state.room=await rpc('alive_timer',{p_code:state.currentRoomCode,p_action:kind,p_seconds:n,p_revision:state.room.revision});refreshControls();});
 w.hostStartTimer=()=>AliveGame.timer('start');w.hostPauseTimer=()=>AliveGame.timer('pause');w.hostResumeTimer=()=>AliveGame.timer('resume');w.hostStopTimer=()=>AliveGame.timer('reset');

 const revealOrder=w.getRevealOrder;
 w.getRevealOrder=(room,players)=>{const order=room.settings?.reveal_orders?.[room.current_round];if(!order)return revealOrder(room,players);const active=players.filter(p=>p.id!==room.host_id&&p.is_alive!==false);return [...order.map(id=>active.find(p=>p.id===id)).filter(Boolean),...active.filter(p=>!order.includes(p.id))];};
 w.hostAdvancePhase=()=>run('phase',async()=>{await refresh();if(!isHost())throw Error('Только ведущий');if(state.room.settings?.tie_pending)throw Error('Ожидается решение держателя «Компромисса»');await rpc('alive_advance',{p_code:state.currentRoomCode,p_revision:state.room.revision});await refresh();await pollTick();});
 AliveGame.tie=target=>run('tie',async()=>{await rpc('alive_resolve_vote',{p_code:state.currentRoomCode,p_choice:target});await refresh();await pollTick();});
 const poll=w.pollTick;
 w.pollTick=()=>run('poll',async()=>{await poll();if(!state.room)return;compact();const p=state.room.settings?.tie_pending;if(p?.holder===state.playerId&&!$('tieDecision')){const el=document.createElement('div');el.id='tieDecision';el.className='panel';el.innerHTML='<h3>Компромисс: ваш выбор</h3>'+p.candidates.map(id=>`<button class="btn btn-primary btn-sm" onclick="AliveGame.tie('${escapeHtml(id)}')">${escapeHtml(state.players.find(p=>p.id===id)?.name||id)}</button>`).join('');$('app').prepend(el);}if(!p)$('tieDecision')?.remove();});
 const render=w.renderGameTable,lobby=w.renderLobby,dynamic=w.updateGameDynamic;
 w.renderGameTable=()=>{render();compact();};w.renderLobby=()=>{lobby();compact();};
 w.updateGameDynamic=async()=>{await dynamic();refreshControls();compact();};
 function makeTabs(container,key,nodes){if(!container||container.dataset.tabbed||nodes.length<2)return;container.dataset.tabbed='true';const nav=document.createElement('div');nav.className='workspace-tabs';nav.setAttribute('role','tablist');container.prepend(nav);const select=i=>{tabs.set(key,i);nodes.forEach((x,j)=>{x.node.hidden=i!==j;nav.children[j].setAttribute('aria-selected',String(i===j));nav.children[j].tabIndex=i===j?0:-1;});};nodes.forEach((x,i)=>{const b=document.createElement('button');b.type='button';b.textContent=x.label;b.setAttribute('role','tab');b.onclick=()=>select(i);b.onkeydown=e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?nodes.length-1:(i+(e.key==='ArrowRight'?1:-1)+nodes.length)%nodes.length;select(next);nav.children[next].focus();}};nav.append(b);});select(Math.min(tabs.get(key)||0,nodes.length-1));}
 function compact(){
  $('app')?.classList.toggle('in-session',!!state.room);const layout=document.querySelector('.game-layout');
  if(layout){
   if(!document.getElementById('mobileWorkspaceTabs')){const nav=document.createElement('nav');nav.id='mobileWorkspaceTabs';nav.className='mobile-workspace-tabs';nav.setAttribute('aria-label','Разделы игры');nav.innerHTML=[['main','Стол'],['aside',isHost()?'Ведущий':'Мои карты'],['sidebar','Бункер / логи']].map(([key,label])=>`<button class="btn btn-ghost btn-sm" data-mobile-tab="${key}" onclick="AliveGame.mobile('${key}')">${label}</button>`).join('');layout.before(nav);}
   AliveGame.mobile(tabs.get('mobile')||(isHost()?'main':'aside'));
   const aside=layout.querySelector('.game-aside'),sidebar=layout.querySelector('.game-sidebar'),chat=$('gameChatMessages')?.closest('.panel');if(chat&&chat.parentElement!==aside)aside?.append(chat);if(aside)makeTabs(aside,'aside',[...aside.children].filter(x=>x.classList.contains('panel')).map((node,i)=>({node,label:i===0?(isHost()?'Ведущий':'Мои карты'):'Чат'})));if(sidebar)makeTabs(sidebar,'sidebar',[...sidebar.children].filter(x=>x.classList.contains('panel')).map((node,i)=>({node,label:['Сценарий','Бункер','Хроника'][i]})));}
  if(state.view==='lobby'){const settings=$('settingsPanel');if(settings&&!settings.dataset.compact){settings.dataset.compact='true';const d=document.createElement('details');d.open=isHost();const s=document.createElement('summary');s.textContent='Настройки игры';d.append(s);d.append($('settingsContent'));settings.replaceChildren(d);}if(isHost()&&$('settingsContent')&&!$('generationSettings'))$('settingsContent').insertAdjacentHTML('beforeend',generationHTML());const actions=document.querySelector('.lobby-actions');if(actions&&isHost()&&!$('cancelStart'))actions.insertAdjacentHTML('beforeend','<button id="cancelStart" class="btn btn-ghost" onclick="cancelGameStart()">Отменить старт</button>');if($('cancelStart'))$('cancelStart').hidden=state.room.phase!=='starting';}
 }
 function generationHTML(){const g=state.room.settings?.generation||{};return `<details id="generationSettings"><summary>Состав колоды и повторы</summary><p class="muted-note">Карт каждого типа на игрока. 0 — не выдавать.</p><div class="generation-grid">${Object.entries(CATEGORY_LABELS).map(([key,label])=>`<label>${escapeHtml(label)}<input data-count-category="${key}" type="number" min="0" max="${['goal','bio'].includes(key)?1:5}" value="${g.counts?.[key]??(key==='goal'&&state.room.card_mode!=='preset'?0:1)}"></label>`).join('')}</div><label>Повторы при раздаче <select id="dealRepeats"><option value="unique" ${g.repeats!=='allow'?'selected':''}>Без повторов в комнате</option><option value="allow" ${g.repeats==='allow'?'selected':''}>Разрешены</option></select></label><label>Повторы при замене спецусловием <select id="effectRepeats"><option value="unique" ${g.effect_repeats!=='allow'?'selected':''}>Только ещё не выданные карты</option><option value="allow" ${g.effect_repeats==='allow'?'selected':''}>Разрешены</option></select></label><button class="btn btn-primary btn-sm" onclick="AliveGame.saveGeneration()">Сохранить состав колоды</button></details>`;}
 AliveGame.saveGeneration=()=>run('settings',async()=>{const counts={};for(const el of document.querySelectorAll('[data-count-category]')){const n=Number(el.value);if(!Number.isInteger(n)||n<0||n>Number(el.max))throw Error('Проверьте количество карт');counts[el.dataset.countCategory]=n;}const generation={counts,repeats:$('dealRepeats').value,effect_repeats:$('effectRepeats').value};await dbUpdateRoom(state.currentRoomCode,{settings:{...state.room.settings,generation}});notice('Состав колоды сохранён. Раздача — для следующей партии, правила замен — сразу.');});
 const master=w.loadHostMasterPanel;
 function masterTabs(){
  const el=$('hostMasterPanel');if(!el||el.dataset.tabbed)return;
  const groups=['Партия','Карты','Настройки','Журнал'].map(label=>({label,node:document.createElement('section')}));
  if(!document.getElementById('liveRevealSchedule'))el.insertAdjacentHTML('beforeend',`<details id="liveRevealSchedule"><summary>Настройки раскрытия по раундам</summary><div id="liveScheduleRows"></div><button class="btn btn-primary btn-sm" onclick="AliveGame.saveSchedule()">Сохранить раскрытия</button></details>`);
  if(!$('liveScheduleRows').children.length)AliveGame.renderSchedule();
  for(const detail of [...el.querySelectorAll(':scope > details')]){
   const title=detail.querySelector('summary')?.textContent||'';
   const index=/Карточки/.test(title)?1:/Настройки|Состав|Справочник/.test(title)?2:/Журнал|Запросы/.test(title)?3:0;
   detail.open=/Модерация|Журнал/.test(title);groups[index].node.append(detail);
  }
  const host=$('hostToolsPanel');
  if(host&&!host.dataset.compact){host.dataset.compact='true';const events=document.createElement('details'),summary=document.createElement('summary');summary.textContent='События и сообщения ведущего';events.append(summary);for(const node of [...host.children])if(node!==el&&node.tagName!=='H2')events.append(node);groups[0].node.append(events);}
  const datalist=el.querySelector('datalist');el.replaceChildren(...groups.map(x=>x.node));if(datalist)el.append(datalist);makeTabs(el,'master',groups);
 }
 const masterObserver=new MutationObserver(()=>{if($('auditLog'))masterTabs();});
 masterObserver.observe(document.getElementById('app'),{childList:true,subtree:true});
 AliveGame.renderSchedule=()=>{const rows=$('liveScheduleRows');if(!rows)return;const rounds=state.room.settings?.rounds||6;rows.innerHTML=Array.from({length:rounds},(_,i)=>{const slots=state.room.settings?.round_reveals?.[i]||['any'];return `<fieldset class="schedule-round" data-round="${i}"><legend>Раунд ${i+1}</legend><label>Раскрытий <input type="number" min="0" max="10" value="${slots.length}" onchange="AliveGame.resizeSchedule(this)"></label><div class="schedule-slots">${slots.map(slot=>scheduleSlot(slot)).join('')}</div></fieldset>`;}).join('');};
 function scheduleSlot(value){return `<select aria-label="Тип раскрытия">${[['any','Любая характеристика'],...Object.entries(CATEGORY_LABELS).filter(([k])=>!['goal','special_condition'].includes(k))].map(([k,label])=>`<option value="${k}" ${value===k?'selected':''}>${escapeHtml(label)}</option>`).join('')}</select>`;}
 AliveGame.resizeSchedule=input=>{const n=Number(input.value);if(!Number.isInteger(n)||n<0||n>10){notice('Количество раскрытий: от 0 до 10',true);return;}const div=input.closest('fieldset').querySelector('.schedule-slots'),slots=[...div.querySelectorAll('select')].map(s=>s.value);div.innerHTML=Array.from({length:n},(_,i)=>scheduleSlot(slots[i]||'any')).join('');};
 AliveGame.saveSchedule=()=>run('settings',async()=>{const round_reveals=[...document.querySelectorAll('.schedule-round')].map(row=>[...row.querySelectorAll('select')].map(x=>x.value));await dbUpdateRoom(state.currentRoomCode,{settings:{...state.room.settings,round_reveals}});notice('Порядок раскрытия обновлён');});
 AliveGame.mobile=view=>{tabs.set('mobile',view);document.querySelector('.game-layout')?.setAttribute('data-mobile-view',view);document.querySelectorAll('[data-mobile-tab]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mobileTab===view)));};
 w.loadHostMasterPanel=async()=>{if(!isHost())return;if($('hostMasterPanel'))delete $('hostMasterPanel').dataset.tabbed;await master();const el=$('hostMasterPanel');if(!el)return;el.insertAdjacentHTML('beforeend',generationHTML()+`<details><summary>Модерация и состав</summary><div id="moderationTools"></div></details><details><summary>Запросы спецусловий</summary><button class="btn btn-sm btn-ghost" onclick="AliveGame.loadRequests()">Обновить</button><div id="effectRequests"></div><h4>Активные условия</h4><div id="activeFlags"></div></details><details><summary>Журнал действий</summary><div class="log-filters"><input id="auditSearch" placeholder="Поиск по журналу" oninput="AliveGame.loadAudit()"><select id="auditKind" onchange="AliveGame.loadAudit()"><option value="">Все действия</option><option value="effect.">Спецусловия</option><option value="vote.">Голосование</option><option value="host.">Ведущий</option><option value="moderation.">Модерация</option><option value="timer.">Таймер</option><option value="game.">Ход игры</option></select><button class="btn btn-sm btn-ghost" onclick="AliveGame.loadAudit()">Обновить</button></div><div id="auditLog"></div></details>`);$('moderationTools').innerHTML=state.players.filter(p=>p.id!==state.room.host_id).map(p=>`<div class="moderation-row"><strong>${escapeHtml(p.name)}</strong><button class="btn btn-sm btn-ghost" onclick="AliveGame.moderate('${p.id}','${p.is_muted?'unmute':'mute'}')">${p.is_muted?'Вернуть чат':'Мут'}</button><button class="btn btn-sm btn-ghost" onclick="AliveGame.moderate('${p.id}','timeout')">Таймаут</button><button class="btn btn-sm btn-ghost" onclick="AliveGame.moderate('${p.id}','untimeout')">Снять таймаут</button><button class="btn btn-sm btn-ghost" onclick="AliveGame.moderate('${p.id}','${p.is_alive?'eliminate':'revive'}')">${p.is_alive?'Изгнать':'Вернуть'}</button></div>`).join('');await Promise.all([AliveGame.loadAudit(),AliveGame.loadRequests(),AliveGame.loadFlags()]);};
 AliveGame.moderate=(target,kind)=>run('moderate',async()=>{let seconds=0;if(kind==='timeout'){const v=prompt('Длительность таймаута в секундах','60');if(v===null)return;seconds=Number(v);if(!Number.isInteger(seconds)||seconds<1||seconds>86400)throw Error('Введите от 1 до 86400 секунд');}await rpc('alive_moderate',{p_code:state.currentRoomCode,p_target:target,p_action:kind,p_seconds:seconds});await refresh();await loadHostMasterPanel();});
 AliveGame.loadRequests=async()=>{if(!$('effectRequests'))return;const {data,error}=await supabaseClient.from('effect_requests').select('*').eq('room_code',state.currentRoomCode).eq('status','pending').order('id');if(error)throw error;$('effectRequests').innerHTML=(data||[]).map(q=>`<div class="audit-row"><b>${escapeHtml(state.players.find(p=>p.id===q.player_id)?.name||'Игрок')}</b> — ${escapeHtml(EFFECT_KEY_DESCRIPTIONS[q.effect_key]||q.effect_key)}<p>Выберите категорию раскрытия или отклоните запрос.</p><button class="btn btn-sm btn-primary" onclick="AliveGame.reviewRequest(${q.id},true)">Рассмотреть</button><button class="btn btn-sm btn-ghost" onclick="AliveGame.reviewRequest(${q.id},false)">Отклонить</button></div>`).join('')||'<p class="muted-note">Нет ожидающих запросов</p>';};
 AliveGame.reviewRequest=(id,approve)=>run('review',async()=>{let resolution;
 if(approve){const {data:q,error}=await supabaseClient.from('effect_requests').select('*').eq('id',id).eq('room_code',state.currentRoomCode).single();if(error)throw error;
 if(q.effect_key==='forced_reveal_category_next_round'){const options=await action('card_options',{target:q.player_id});const selected=await AliveEffectsUI.pickTrait(options.filter(c=>!c.revealed&&!['goal','special_condition'].includes(c.category)),'Ведущий выбирает категорию следующего раскрытия');if(!selected)return;resolution=selected.category+': назначено ведущим';}}
 resolution=resolution||prompt(approve?'Какие изменения вы внесли?':'Почему запрос отклонён?');if(!resolution)return;await rpc('alive_review_effect',{p_code:state.currentRoomCode,p_id:id,p_approve:approve,p_resolution:resolution});await AliveGame.loadRequests();await AliveGame.loadAudit();});
 AliveGame.loadAudit=async()=>{if(!$('auditLog'))return;const {data,error}=await supabaseClient.from('game_events').select('*').eq('room_code',state.currentRoomCode).order('id',{ascending:false}).limit(300);if(error)throw error;const search=($('auditSearch')?.value||'').toLowerCase(),kind=$('auditKind')?.value||'';const filtered=(data||[]).filter(e=>(!kind||e.event_key?.startsWith(kind))&&e.text.toLowerCase().includes(search));$('auditLog').innerHTML=filtered.map(e=>`<div class="audit-row"><small>Раунд ${e.round??'—'} · ${new Date(e.created_at).toLocaleTimeString('ru')} ${e.private?'· приватно':''}</small><p>${escapeHtml(e.text)}</p>${Object.keys(e.event_params||{}).length?`<details><summary>Подробности</summary><pre>${escapeHtml(JSON.stringify(e.event_params,null,2))}</pre></details>`:''}</div>`).join('')||'<p class="muted-note">Нет событий по фильтру</p>';};

 AliveGame.loadFlags=async()=>{if(!$('activeFlags'))return;const {data,error}=await supabaseClient.from('round_effects').select('*').eq('room_code',state.currentRoomCode).eq('is_active',true).order('id');if(error)throw error;$('activeFlags').innerHTML=(data||[]).map(f=>'<div class="audit-row"><b>'+escapeHtml(EFFECT_KEY_DESCRIPTIONS[f.effect_key]||f.effect_key)+'</b><p>'+escapeHtml(state.players.find(p=>p.id===f.target_player_id)?.name||'Вся комната')+' · '+(f.round?'Раунд '+f.round:'Постоянно')+'</p><button class="btn btn-sm btn-ghost" onclick="AliveGame.clearFlag('+f.id+')">Снять условие</button></div>').join('')||'<p class="muted-note">Нет активных условий</p>';};
 AliveGame.clearFlag=id=>run('flag',async()=>{await action('clear_flag',{id});await AliveGame.loadFlags();await AliveGame.loadAudit();});
 const editor=w.loadHostCardEditor;
 w.loadHostCardEditor=async player=>{await editor(player);if(!player||!isHost())return;$('hostCardEditorList').insertAdjacentHTML('afterbegin',`<div class="card-add"><select id="newCardCategory">${Object.entries(CATEGORY_LABELS).map(([k,v])=>`<option value="${k}">${escapeHtml(v)}</option>`).join('')}</select><textarea id="newCardText" placeholder="Текст новой карты"></textarea><button class="btn btn-sm btn-primary" onclick="AliveGame.addCard('${player}')">Добавить карту</button></div>`);};
 AliveGame.addCard=player=>run('card',async()=>{const category=$('newCardCategory').value,text=$('newCardText').value.trim();if(!text)throw Error('Введите текст карты');const {data,error}=await supabaseClient.from('player_cards').select('slot').eq('room_code',state.currentRoomCode).eq('player_id',player).eq('category',category).order('slot',{ascending:false}).limit(1);if(error)throw error;const slot=(data?.[0]?.slot||0)+1;if(['goal','bio'].includes(category)&&slot>1)throw Error('Эта категория допускает одну карту');const result=await supabaseClient.from('player_cards').insert({room_code:state.currentRoomCode,player_id:player,category,slot,text,value:0});if(result.error)throw result.error;await loadHostCardEditor(player);});
 for(const name of ['actionSaveSettings','actionHostSaveLiveSettings','actionHostSaveCard','actionKick','actionToggleMute','actionTimeout','actionSendChat','actionSendGameChat']){const fn=w[name];if(typeof fn==='function')w[name]=(...args)=>run(name,()=>fn(...args));}
 w.addEventListener('unhandledrejection',e=>notice(e.reason?.message||'Не удалось обновить данные',true));
})(window);
