(function(w){
 'use strict';
 const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const db=w.supabase.createClient(w.MAFIA_CONFIG.url,w.MAFIA_CONFIG.key);
 let session,game,roles={},labels={},mediaConfigured=false,room=null,connectedEpoch=null,mediaWanted=false,connecting=false,polling=false,actionBusy=false,busyAction='',cameraCheckPromise=null,settingsKey='',actionKey='';let mobilePhase=null;
 let videoRoom=null,videoRoomName=null;let audioMuted=false;const remoteAudio=new Map();
 let lastCue=null,presenceBusy=false,lastPresence=0,hostKey='',roundFilter='all',finalKey='';
 const apiURL=w.MAFIA_CONFIG.url+'/functions/v1/mafia';
 function notice(text){$('notice').textContent=text;$('notice').hidden=false;clearTimeout(notice.timer);notice.timer=setTimeout(()=>$('notice').hidden=true,9000);}
 async function api(op,data={}){const auth=await db.auth.getSession();session=auth.data.session;if(!session)throw Error('Сессия истекла. Обновите страницу.');const response=await fetch(apiURL,{method:'POST',headers:{Authorization:'Bearer '+session.access_token,apikey:w.MAFIA_CONFIG.key,'Content-Type':'application/json'},body:JSON.stringify({op,code:game?.code,epoch:game?.epoch,...data})});const result=await response.json();if(!response.ok||result.error)throw Error(result.error||'Не удалось выполнить действие');if(result.game&&!['presence','camera_status'].includes(op)){game=result.game;localStorage.setItem('mafiaRoom',game.code);}if(result.mediaConfigured!==undefined)mediaConfigured=result.mediaConfigured;return result;}
 async function run(fn,label=''){if(actionBusy)return;actionBusy=true;busyAction=label;if(label)render();try{await fn();}catch(e){notice(e.message);}finally{actionBusy=false;busyAction='';render();}}
 function home(){game=null;w.MafiaSignals.observe(null);$('mafiaApp').innerHTML=`<div class="welcome"><p class="eyebrow">КАМЕРЫ ВКЛЮЧЕНЫ. РОЛИ СКРЫТЫ.</p><h1>У каждого<br>есть <em>тайна.</em></h1><p class="intro">Город засыпает, и правила меняются.<br>Автоматическая «Мафия» с голосом и видео.</p><div id="entry"><label for="playerName">Ваше имя</label><div class="entry-row"><input id="playerName" maxlength="20" autocomplete="nickname" value="${esc(localStorage.getItem('playerName')||'')}" placeholder="Как вас называть"><button class="primary" onclick="Mafia.create()">Создать комнату</button></div><div class="entry-row"><input id="roomCode" maxlength="6" placeholder="Код комнаты · 6 символов" aria-label="Код комнаты"><button onclick="Mafia.join()">Присоединиться</button></div><p class="hint">Камера обязательна для игры. Режим ночных камер выбирается в лобби. Запись не ведётся.</p>${!mediaConfigured?'<p class="night-cover">Игровой сервер доступен. Видеосвязь ожидает настройки LiveKit Cloud администратором.</p>':''}<div id="soundSettings"></div><details class="panel"><summary>22 роли вашего города</summary><div class="catalog">${Object.values(roles).map(r=>`<article><h4>${esc(r[0])}</h4><p>${esc(r[3])}</p></article>`).join('')}</div></details></div></div>`;w.MafiaSignals.mount($('soundSettings'));}
 function shell(){settingsKey='';actionKey='';hostKey='';roundFilter='all';lastCue=null;$('mafiaApp').innerHTML=`<section class="workspace"><div class="phase-bar"><div><p class="eyebrow" id="roomLabel"></p><h2 id="phaseLabel"></h2></div><div class="phase-clock" id="phaseClock"></div></div><div id="nightNotice"></div><div id="wakeNotice" role="status"></div><div id="finalScreen"></div><nav id="mobileTabs"><button onclick="Mafia.mobile('table')">Стол</button><button onclick="Mafia.mobile('action')">Роль и ход</button><button onclick="Mafia.mobile('log')">Хроника</button></nav><div class="layout" id="mafiaLayout" data-mobile-view="table"><div><div class="video-grid" id="videoGrid"></div><div class="toolbar" id="toolbar"></div><div id="soundSettings"></div><div id="hostControls"></div><div id="settings"></div></div><aside class="aside"><section class="panel" id="myRole"></section><section class="panel"><h3>Ваш ход</h3><div id="actions" class="actions"></div></section><section class="panel"><h3>Личные сведения</h3><div id="privateInfo"></div></section><section class="panel"><h3>Хроника города</h3><select id="chronicleRound" aria-label="Раунд хроники" onchange="Mafia.chronicle(this.value)"></select><div id="events"></div></section></aside></div></section>`;}
 function render(){if(!game)return;if(!$('videoGrid'))shell();const me=game.players.find(p=>p.id===game.me.id),host=game.host===game.me.id;
  $('roomLabel').textContent='КОМНАТА '+game.code+' · '+game.players.length+' УЧАСТНИКОВ · '+(game.settings.cameraMode==='open'?'КАМЕРЫ ВСЕГДА ВИДНЫ':'КАМЕРЫ СКРЫТЫ НОЧЬЮ');$('phaseLabel').textContent=game.paused?'Пауза':({lobby:'Город собирается',night:'Ночь '+game.round,day:'День '+game.round,voting:'Голосование',result:'Итоги дня',finished:'Партия завершена'}[game.phase]||'Мафия');clock();
  $('nightNotice').innerHTML=game.paused?`<div class="night-cover">${esc(game.pauseReason)}</div>`:game.phase==='night'&&game.media.videoRoom?'<div class="night-cover">Камеры открыты. Закройте глаза и открывайте их только в своё пробуждение. Ночные разговоры и выборы скрыты.</div>':game.phase==='night'&&!game.wake?'<div class="night-cover">Город спит. Чужие ночные действия и результаты скрыты. Дождитесь рассвета.</div>':'';
  const current=new Map([...$('videoGrid').children].map(el=>[el.dataset.id,el]));
  for(const p of game.players){let tile=current.get(p.id);if(!tile){tile=document.createElement('article');tile.dataset.id=p.id;tile.innerHTML='<div class="player-placeholder"><b></b><span></span></div><div class="video-slot"></div><div class="device-badges"></div><div class="player-name"><strong></strong><span class="player-badge"></span></div>';$('videoGrid').append(tile);}current.delete(p.id);tile.className='player-tile'+(p.id===game.me.id?' me':'')+(!p.alive?' dead':'');tile.querySelector('.player-placeholder b').textContent=String(p.seat).padStart(2,'0');tile.querySelector('.player-placeholder span').textContent=!p.alive?'Наблюдатель':game.phase==='night'&&!game.media.videoRoom&&!game.me.nightPeers.includes(p.id)?'Город спит':'Ожидаем камеру';tile.querySelector('strong').textContent=p.name+(p.id===game.me.id?' · Вы':'');tile.querySelector('.player-badge').textContent=game.phase==='finished'?roles[p.role]?.[0]||'':game.phase==='lobby'?(p.ready?'ГОТОВ':'В ЛОББИ'):p.silenced?'БЕЗ ГОЛОСА':p.alibi?'АЛИБИ':'';}
  for(const tile of current.values())tile.remove();
  $('toolbar').innerHTML=`<button class="${room?.state==='connected'?'':'primary'}" onclick="Mafia.camera()">${room?.state==='connected'?'Камера подключена':'Подключить камеру'}</button><button onclick="Mafia.microphone()" ${!room||!game.media.audio?'disabled':''}>${room?.localParticipant?.isMicrophoneEnabled?'Выключить микрофон':'Включить микрофон'}</button><button id="audioToggle" onclick="Mafia.audio()" aria-describedby="audioStatus">Включить звук</button>${game.phase==='lobby'?`<button id="readyButton" class="primary" onclick="Mafia.ready()" ${actionBusy?'disabled':''}>${busyAction==='ready'?'Проверяем камеру…':me.ready?'Не готов':'Я готов'}</button>${host?`<button id="startButton" onclick="Mafia.start()" ${actionBusy?'disabled':''}>${busyAction==='start'?'Проверяем игроков…':'Начать партию'}</button>`:''}`:host&&game.phase!=='finished'?`<button onclick="Mafia.pause()">${game.paused?'Продолжить':'Пауза'}</button>`:''}<button onclick="Mafia.exit()">В меню</button><span id="audioStatus" class="hint" role="status"></span>`;
  renderAudioControls();
  $('myRole').innerHTML=game.me.role?`<p class="eyebrow">ТОЛЬКО ДЛЯ ВАС</p><div class="role-name">${esc(roles[game.me.role]?.[0])}</div><p class="hint">${esc(roles[game.me.role]?.[3])}</p>`:'<h3>Ваша роль</h3><p class="muted">Появится после начала партии. Создатель комнаты тоже играет и не знает чужих ролей.</p>';
  $('privateInfo').innerHTML=game.me.inbox.length?game.me.inbox.slice(-6).reverse().map(m=>`<div class="private-note"><small>Ночь ${m.round}</small><br>${esc(m.text)}</div>`).join(''):'<p class="hint">Результаты ваших проверок появятся здесь.</p>';
  w.MafiaSignals.mount($('soundSettings'),game.phase==='lobby');renderChronicle();renderWake();renderFinal();renderHost(host);renderDevices();
  renderSettings(host);renderActions();renderSaved();if(mobilePhase!==game.phase){mobilePhase=game.phase;mobile(['night','voting'].includes(game.phase)?'action':'table');}
  if(mediaWanted&&!connecting&&(connectedEpoch!==game.epoch||(game.media.videoRoom&&videoRoom?.state!=='connected')))connect().catch(e=>notice(e.message));
  reportPresence();
 }
 function mobile(view){$('mafiaLayout')?.setAttribute('data-mobile-view',view);document.querySelectorAll('#mobileTabs button').forEach((b,i)=>b.setAttribute('aria-pressed',String(['table','action','log'][i]===view)));}
 function renderSettings(host){const key=JSON.stringify([host,game.phase,game.settings]);if(key===settingsKey)return;settingsKey=key;
  if(!host||game.phase!=='lobby'){$('settings').innerHTML='';return;}
  $('settings').innerHTML=`<details class="panel settings-panel" open><summary>Состав ролей и время</summary><p class="hint">Незаполненные места станут обычными мирными. Мафии должно быть меньше половины. Масоны — только при 17+ участниках.</p><div class="role-grid">${Object.entries(roles).map(([key,r])=>`<label>${esc(r[0])}<input type="number" min="0" max="${['mafia','citizen','mason'].includes(key)?24:1}" data-role="${key}" aria-label="${esc(r[0])}" value="${game.settings.counts[key]||0}"></label>`).join('')}</div><label for="setting-cameraMode">Камеры ночью</label><select id="setting-cameraMode"><option value="hidden" ${(game.settings.cameraMode||'hidden')==='hidden'?'selected':''}>Скрывать чужие камеры ночью</option><option value="open" ${game.settings.cameraMode==='open'?'selected':''}>Камеры видны всегда — закрываем глаза сами</option></select><p class="hint">При открытых камерах все видят видео друг друга, включая выбывших. Ночные разговоры и действия остаются приватными.</p><div class="duration-grid">${[['daySeconds','Обсуждение, сек.'],['voteSeconds','Голосование, сек.'],['nightSeconds','На пробуждение, сек.'],['bonusSeconds','Завершение ночи, сек.'],['maxPlayers','Максимум игроков']].map(([k,label])=>`<label>${label}<input id="setting-${k}" type="number" value="${game.settings[k]}"></label>`).join('')}</div><button class="primary" onclick="Mafia.settings()">Сохранить настройки</button><p class="hint">Изменение настроек снимает готовность со всех игроков.</p></details>`;
 }
 function renderActions(){const key=JSON.stringify([game.phase,game.epoch,game.paused,game.me.actions,game.wake?.key,game.eligibleTargets,game.me.voted,game.me.alive,game.players.map(p=>[p.id,p.alive,p.alibi,p.silenced])]);if(key===actionKey)return;actionKey=key;
  if(game.phase==='finished'){$('actions').innerHTML='<p class="muted">Игра завершена. Можно обсудить итоги и посмотреть хронику.</p>';return;}
  if(!game.me.alive){$('actions').innerHTML='<p class="muted">Вы выбыли. Ночные решения живых игроков остаются скрытыми.</p>';return;}
  if(game.paused){$('actions').innerHTML='<p class="muted">Партия на паузе.</p>';return;}
  if(game.phase==='voting'){
   if(game.me.voted){$('actions').innerHTML='<p>Голос принят. Дождитесь результата.</p>';return;}
   if(game.players.find(p=>p.id===game.me.id)?.silenced){$('actions').innerHTML='<p>Сегодня вы лишены права голоса.</p>';return;}
   $('actions').innerHTML=`<select id="voteTarget" aria-label="Кандидат"><option value="">Воздержаться</option>${game.players.filter(p=>p.alive&&!p.alibi&&p.id!==game.me.id).map(p=>`<option value="${p.id}">№${p.seat} ${esc(p.name)}</option>`).join('')}</select><button class="primary" onclick="Mafia.vote()">Подтвердить голос</button>`;return;
  }
  if(!game.me.actions.length){$('actions').innerHTML='<p class="muted">'+(game.phase==='night'?(game.wake?'Сейчас: '+esc(game.wake.label)+'. Дождитесь своего пробуждения.':'Спите спокойно. Дождитесь рассвета.'):game.phase==='lobby'?'Подключите камеру и подтвердите готовность.':'Обсуждайте подозрения с городом.')+'</p>';return;}
  $('actions').innerHTML=`<div class="ability-list">${game.me.actions.map(k=>`<button type="button" data-ability="${k}" onclick="Mafia.ability('${k}')">${esc(labels[k]||k)}</button>`).join('')}</div><select id="nightKind" class="sr-only" aria-label="Ночная способность" onchange="Mafia.targets()">${game.me.actions.map(k=>`<option value="${k}">${esc(labels[k]||k)}</option>`).join('')}</select><div id="nightTargets"></div><button id="confirmAction" class="primary" onclick="Mafia.act()">Подтвердить выбор</button><div id="submittedInfo" class="saved-choice"></div><p class="hint">Нет выбора к концу пробуждения — допустимая цель выбирается случайно. Способности без цели подтверждаются вручную.</p>`;
  const submitted=game.me.submitted;if(submitted&&game.me.actions.includes(submitted.kind))$('nightKind').value=submitted.kind;targets();
 }
 function targets(){const kind=$('nightKind')?.value;if(!kind)return;const count=['alert','ignite'].includes(kind)?0:kind==='compare'?2:1;const allowed=game.eligibleTargets?.[kind];
  const available=game.players.filter(p=>allowed?allowed.includes(p.id):(kind==='autopsy'?!p.alive:p.alive)&&(p.id!==game.me.id||['heal','pardon'].includes(kind)));
  document.querySelectorAll('[data-ability]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.ability===kind)));
  $('nightTargets').innerHTML=Array.from({length:count},(_,i)=>`<label>${count>1?'Цель '+(i+1):'Цель'}<select id="nightTarget${i}" aria-label="Цель ${i+1}" onchange="Mafia.highlightTargets()"><option value="">Выберите игрока</option>${available.map(p=>`<option value="${p.id}">№${p.seat} ${esc(p.name)}</option>`).join('')}</select></label>`).join('')+(count===1?`<div class="target-grid">${available.map(p=>`<button type="button" data-target="${p.id}" onclick="Mafia.target('${p.id}')"><small>№${p.seat}</small> ${esc(p.name)}</button>`).join('')}</div>`:'');
  const selected=kind==='bonus_vote'?game.me.bonusVote?[game.me.bonusVote]:[]:kind==='mafia_vote'?game.me.mafiaVote?[game.me.mafiaVote]:[]:game.me.submitted?.kind===kind?game.me.submitted.targets:[];
  selected.forEach((id,i)=>{if($('nightTarget'+i)&&available.some(p=>p.id===id))$('nightTarget'+i).value=id;});highlightTargets();
 }
 function highlightTargets(){const selected=[...document.querySelectorAll('#nightTargets select')].map(el=>el.value);document.querySelectorAll('[data-target]').forEach(b=>b.setAttribute('aria-pressed',String(selected.includes(b.dataset.target))));const kind=$('nightKind')?.value;if($('confirmAction'))$('confirmAction').disabled=selected.some(v=>!v)||new Set(selected).size!==selected.length||(kind==='ignite'&&!game.me.marked.length);}
 function renderSaved(){if(!$('submittedInfo'))return;const describe=(kind,targets)=>esc(labels[kind]||kind)+(targets.length?' → '+targets.map(id=>esc(game.players.find(p=>p.id===id)?.name||'Игрок')).join(', '):'');const lines=[];
  if(game.me.bonusVote)lines.push(describe('bonus_vote',[game.me.bonusVote]));if(game.me.mafiaVote)lines.push(describe('mafia_vote',[game.me.mafiaVote]));if(game.me.submitted)lines.push(describe(game.me.submitted.kind,game.me.submitted.targets));$('submittedInfo').innerHTML=lines.length?'Сохранено: '+lines.join('<br>'):'Выбор ещё не подтверждён.';
 }

 function clock(){if(!$('phaseClock')||!game)return;w.MafiaSignals.observe(game);const n=Math.max(0,Math.ceil(((game.wake?.deadline||game.deadline)-Date.now())/1000));$('phaseClock').textContent=game.phase==='finished'?'':game.paused?'Ⅱ':!game.deadline?'':n?Math.floor(n/60)+':'+String(n%60).padStart(2,'0'):'Обработка…';}
 function mediaConnected(){return room?.state==='connected'&&connectedEpoch===game?.epoch;}
 function renderDevices(){if(!game||!$('videoGrid'))return;
  const svg=body=>'<svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true">'+body+'</svg>';
  const icons={sound:svg('<path d="M11 4 5 9H2v6h3l6 5zM15 8q5 4 0 8M18 4q9 8 0 16"/>'),mic:svg('<rect x="8" y="2" width="8" height="13" rx="4"/><path d="M5 10v2a7 7 0 0 0 14 0v-2M12 19v3M8 22h8"/>'),camera:svg('<rect x="2" y="5" width="14" height="14" rx="2"/><path d="m16 9 6-4v14l-6-4"/>')};
  for(const tile of $('videoGrid').children){const p=game.players.find(p=>p.id===tile.dataset.id);if(!p)continue;const own=p.id===game.me.id,hidden=game.phase==='night'&&!own&&!game.me.nightPeers.includes(p.id);
   const participant=mediaConnected()?(own?room.localParticipant:room.remoteParticipants?.get(p.id)):null;
   const values={sound:hidden?null:own?mediaConnected()&&game.media.subscribe&&!audioMuted&&room.canPlaybackAudio:p.sound,mic:hidden?null:participant?!!participant.isMicrophoneEnabled:mediaConnected()?false:null,camera:game.media.videoRoom?(videoRoom?.state==='connected'?(own?!!videoRoom.localParticipant.isCameraEnabled:videoRoom.remoteParticipants?.has(p.id)?!!videoRoom.remoteParticipants.get(p.id).isCameraEnabled:false):null):hidden?null:participant?!!participant.isCameraEnabled:mediaConnected()?false:null};
   const labels={sound:'Звук',mic:'Микрофон',camera:'Камера'};tile.querySelector('.device-badges').innerHTML=Object.entries(values).map(([key,value])=>{const state=value==null?'скрыто / нет данных':value?'включён':'выключен',text=labels[key]+': '+state;return `<span class="device ${value==null?'unknown':value?'on':'off'}" title="${text}" aria-label="${text}"><span aria-hidden="true">${icons[key]}</span><small>${value==null?'?':value?'●':'×'}</small></span>`;}).join('');
  }
 }
 async function reportPresence(force=false){if(!game||presenceBusy||(!force&&Date.now()-lastPresence<15000))return;presenceBusy=true;try{await api('presence',{sound:!!(mediaConnected()&&game.media.subscribe&&!audioMuted&&room.canPlaybackAudio)});lastPresence=Date.now();}catch{}finally{presenceBusy=false;}}
 function renderWake(){const wake=game.wake,own=!!wake?.mine&&!game.paused;const key=[game.phase,game.round,wake?.key,own,game.paused].join(':');
  if($('wakeNotice').dataset.key!==key){$('wakeNotice').dataset.key=key;$('wakeNotice').innerHTML=game.phase==='night'&&wake?`<div class="wake-banner ${own?'your-turn':''}"><div><small>ПРОБУЖДЕНИЕ ${wake.index+1} / ${wake.total}</small><strong>${own?'Ваш ход':esc(wake.label)}</strong><span>${own?'Выберите действие и подтвердите цель.':'Чужие ночные действия и их исполнители скрыты.'}</span></div><details><summary>Порядок ночи</summary><ol>${wake.order.map((step,i)=>`<li class="${i===wake.index?'current':''}">${esc(step.label)}</li>`).join('')}</ol></details></div>`:'';}
  $('actions').closest('.panel').classList.toggle('your-turn',own);const cue=[game.phase,game.round,wake?.key,own,game.paused].join(':');
  if(cue!==lastCue){lastCue=cue;if(own)mobile('action');}
  document.title=(own?'Ваш ход · ':game.phase==='finished'?'Итоги · ':'')+'Мафия — Город грехов';
 }
 function renderChronicle(){const select=$('chronicleRound'),rounds=[...new Set(game.events.map(e=>e.round))].sort((a,b)=>b-a);const options='<option value="all">Все раунды</option>'+rounds.map(n=>`<option value="${n}">${n?'Раунд '+n:'Лобби'}</option>`).join('');if(select.innerHTML!==options)select.innerHTML=options;select.value=roundFilter;
  const visible=game.events.filter(e=>roundFilter==='all'||String(e.round)===roundFilter);$('events').innerHTML=visible.slice().reverse().map(e=>`<div class="event ${e.private?'private-event':''}"><small>Раунд ${e.round}${e.private?' · Личная / клановая запись':''}</small><br>${esc(e.text)}</div>`).join('')||'<p class="hint">В этом раунде пока нет событий.</p>';
 }
 function renderFinal(){if(!game.winner){finalKey='';$('finalScreen').innerHTML='';return;}const key=JSON.stringify([game.code,game.winner]);if(finalKey===key&&$('finalScreen').children.length)return;finalKey=key;const winner=game.winner,won=winner.ids.includes(game.me.id),draw=winner.side==='draw';const people=game.players.filter(p=>winner.ids.includes(p.id));
  $('finalScreen').innerHTML=`<section class="final-screen ${won?'won':''}"><p class="eyebrow">ГОРОД ВЫНЕС СВОЙ ВЕРДИКТ</p><h2>${draw?'До рассвета не дожил никто':won?'Поздравляем с победой!':'Партия завершена'}</h2><p>${esc(winner.text)}</p><div class="winner-list">${people.map(p=>`<article><small>№${p.seat} · ПОБЕДИТЕЛЬ</small><strong>${esc(p.name)}</strong><span>${esc(roles[p.role]?.[0]||'')}</span></article>`).join('')}</div><details><summary>Все роли этой партии</summary><div class="final-roster">${game.players.map(p=>`<div><strong>${esc(p.name)}</strong><span>${esc(roles[p.role]?.[0]||'')} ${p.alive?'· выжил(а)':'· выбыл(а)'}</span></div>`).join('')}</div></details><button onclick="Mafia.showChronicle()">Посмотреть хронику</button><button onclick="Mafia.exit()">Вернуться в меню</button></section>`;
 }
 function renderHost(host){const key=[host,game.phase,game.epoch].join(':');if(key===hostKey)return;hostKey=key;const box=$('hostControls');if(!host||['lobby','finished'].includes(game.phase)){box.innerHTML='';return;}
  box.innerHTML=`<details class="host-recovery"><summary>Ручное управление</summary><p class="hint">Переходы выполняют обычные правила и подсчёт. Назад действия не откатываются.</p><div class="toolbar"><button onclick="Mafia.control('next')">Следующий этап</button>${game.phase==='night'?'<button onclick="Mafia.control(\'dawn\')">Завершить ночь</button>':''}${game.phase==='day'?'<button onclick="Mafia.control(\'voting\')">К голосованию</button>':''}<button onclick="Mafia.control('next_round')">Следующий раунд</button><label>Осталось, сек. <input id="manualSeconds" type="number" min="5" max="900" value="30"></label><button onclick="Mafia.control('timer')">Задать время</button></div></details>`;
 }
 function renderAudioControls(){const button=$('audioToggle'),status=$('audioStatus');if(!button||!game)return;
  const connected=mediaConnected(),allowed=game.media.subscribe,on=connected&&allowed&&!audioMuted&&room.canPlaybackAudio;
  button.disabled=!connected||!allowed;button.textContent=!allowed?'Звук недоступен':on?'Выключить звук':'Включить звук';button.setAttribute('aria-pressed',String(!!on));
  status.textContent=!connected?'Для звука подключите камеру.':!allowed?(game.phase==='night'?'Ночью чужой звук скрыт для вашей роли.':'Выбывшие игроки не слышат живых до конца партии.'):audioMuted?'Звук выключен у вас.':!room.canPlaybackAudio?'Браузер ожидает нажатия «Включить звук».':remoteAudio.size?'Звук включён.':'Звук включён. Ожидаем микрофоны других игроков.';
 }
 function applyAudioVolume(){for(const [track,el] of remoteAudio){track.setVolume(audioMuted?0:1);el.muted=audioMuted;}renderDevices();reportPresence(true);}
 async function toggleAudio(){if(!mediaConnected())throw Error('Сначала подключите камеру');if(!game.media.subscribe)throw Error('Сейчас чужой звук недоступен по правилам игры');
  if(!audioMuted&&room.canPlaybackAudio){audioMuted=true;applyAudioVolume();renderAudioControls();return;}
  audioMuted=false;applyAudioVolume();
  try{await room.startAudio();if(!room.canPlaybackAudio)throw Error('Браузер заблокировал звук. Разрешите воспроизведение звука для сайта и повторите.');}
  finally{applyAudioVolume();renderAudioControls();}
 }
 function attach(track,participant){if(track.kind==='audio'){if(participant.identity===game.me.id||remoteAudio.has(track))return;track.setVolume(audioMuted?0:1);const el=track.attach();el.muted=audioMuted;el.dataset.track=track.sid||'';remoteAudio.set(track,el);$('audioTracks').append(el);renderAudioControls();return;}const tile=[...$('videoGrid').children].find(el=>el.dataset.id===participant.identity);if(tile){const video=track.attach();video.autoplay=true;video.playsInline=true;video.muted=participant.identity===game.me.id;tile.querySelector('.video-slot').replaceChildren(video);}}
 function bindRoom(target,videoOnly=false){const lk=w.LivekitClient;
  target.on(lk.RoomEvent.TrackSubscribed,(track,pub,p)=>{if(!videoOnly||track.kind==='video')attach(track,p);});
  target.on(lk.RoomEvent.TrackUnsubscribed,track=>{track.detach().forEach(el=>el.remove());remoteAudio.delete(track);renderAudioControls();renderDevices();});
  target.on(lk.RoomEvent.LocalTrackPublished,pub=>{if(pub.track)attach(pub.track,target.localParticipant);});
  if(!videoOnly)target.on(lk.RoomEvent.AudioPlaybackStatusChanged,()=>{renderAudioControls();renderDevices();reportPresence(true);});
  for(const name of ['TrackMuted','TrackUnmuted','TrackPublished','TrackUnpublished','ParticipantConnected','ParticipantDisconnected','ConnectionStateChanged'])if(lk.RoomEvent[name])target.on(lk.RoomEvent[name],renderDevices);
  target.on(lk.RoomEvent.Disconnected,()=>{if(!videoOnly&&room===target)connectedEpoch=null;renderAudioControls();renderDevices();});
 }
 function verifyCamera(attempt=0){if(cameraCheckPromise||!game||game.phase!=='lobby')return cameraCheckPromise;cameraCheckPromise=api('camera_status').catch(()=>{if(attempt<2&&!actionBusy)setTimeout(()=>verifyCamera(attempt+1),700*(attempt+1));}).finally(()=>cameraCheckPromise=null);return cameraCheckPromise;}
 async function connect(){if(connecting||!game)return;connecting=true;mediaWanted=true;try{
  const result=await api('media');if(room)await room.disconnect();remoteAudio.clear();$('audioTracks').replaceChildren();
  const lk=w.LivekitClient;if(!lk)throw Error('Не загрузилась библиотека видеосвязи');
  const video=result.connection.video,keepVideo=video&&videoRoom?.state==='connected'&&videoRoomName===video.room;
  if(!keepVideo){if(videoRoom)await videoRoom.disconnect();videoRoom=null;videoRoomName=null;document.querySelectorAll('.video-slot').forEach(el=>el.replaceChildren());}
  if(video&&!keepVideo){videoRoom=new lk.Room({adaptiveStream:true,dynacast:true,videoCaptureDefaults:{resolution:lk.VideoPresets.h360.resolution}});bindRoom(videoRoom,true);await videoRoom.connect(video.url,video.token);await videoRoom.localParticipant.setCameraEnabled(true);videoRoomName=video.room;}
  room=new lk.Room({adaptiveStream:true,dynacast:true,videoCaptureDefaults:{resolution:lk.VideoPresets.h360.resolution}});bindRoom(room);
  await room.connect(result.connection.url,result.connection.token);if(!video)await room.localParticipant.setCameraEnabled(true);connectedEpoch=result.connection.epoch;
  if(game.media.audio)await room.localParticipant.setMicrophoneEnabled(true);render();reportPresence(true);verifyCamera();
 }catch(e){connectedEpoch=null;mediaWanted=false;throw e;}finally{connecting=false;}}
 async function poll(){if(!game||polling||actionBusy)return;polling=true;try{await api('state');render();}catch(e){if(!/занята обновлением/.test(e.message))notice(e.message);}finally{polling=false;}}
 w.Mafia={
  create:()=>run(async()=>{const name=$('playerName').value.trim();await api('create',{name});localStorage.setItem('playerName',name);shell();}),
  join:()=>run(async()=>{const name=$('playerName').value.trim(),code=$('roomCode').value.trim();await api('join',{name,code});localStorage.setItem('playerName',name);shell();}),
  camera:()=>run(connect),microphone:()=>run(async()=>{if(room&&game.media.audio)await room.localParticipant.setMicrophoneEnabled(!room.localParticipant.isMicrophoneEnabled);}),audio:()=>run(toggleAudio),
  ready:()=>run(async()=>{if(cameraCheckPromise)await cameraCheckPromise;await api('ready',{ready:!game.players.find(p=>p.id===game.me.id).ready});},'ready'),start:()=>run(async()=>{await api('start');},'start'),
  pause:()=>run(async()=>{await api(game.paused?'resume':'pause');}),
  settings:()=>run(async()=>{const settings=structuredClone(game.settings);settings.cameraMode=$('setting-cameraMode').value;settings.counts={};document.querySelectorAll('[data-role]').forEach(el=>settings.counts[el.dataset.role]=Number(el.value));for(const k of ['daySeconds','voteSeconds','nightSeconds','bonusSeconds','maxPlayers'])settings[k]=Number($('setting-'+k).value);await api('settings',{settings});}),
  targets,mobile,showChronicle:()=>{mobile('log');$('events')?.closest('section').scrollIntoView({block:'center',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});},highlightTargets,ability:kind=>{$('nightKind').value=kind;targets();},target:id=>{$('nightTarget0').value=id;highlightTargets();},chronicle:value=>{roundFilter=value;renderChronicle();},
  control:command=>run(async()=>{if(!confirm(command==='timer'?'Изменить оставшееся время?':'Перейти дальше? Незавершённые выборы будут обработаны по правилам таймера.'))return;await api('control',{command,seconds:Number($('manualSeconds')?.value)});}),
  act:()=>run(async()=>{const kind=$('nightKind').value,targets=[...document.querySelectorAll('#nightTargets select')].map(el=>el.value);await api('act',{kind,targets});notice('Ночной выбор сохранён');}),
  vote:()=>run(async()=>{const target=$('voteTarget').value;await api('act',{kind:'vote',targets:target?[target]:[]});}),
  exit:()=>run(async()=>{if(game.phase!=='finished'&&!confirm(game.phase==='lobby'?'Покинуть комнату?':'Выйти в меню? Без вашей камеры партия будет ожидать подключения.'))return;if(game.phase==='lobby')await api('leave');mediaWanted=false;if(room)await room.disconnect();if(videoRoom)await videoRoom.disconnect();room=null;videoRoom=null;videoRoomName=null;remoteAudio.clear();$('audioTracks').replaceChildren();localStorage.removeItem('mafiaRoom');home();})
 };
 async function boot(){try{let auth=await db.auth.getSession();session=auth.data.session;if(!session){auth=await w.AliveAuth.signInAnonymously(db);if(auth.error)throw auth.error;session=auth.data.session;}const catalog=await api('catalog');roles=catalog.roles;labels=catalog.actions;const saved=localStorage.getItem('mafiaRoom');if(saved){try{await api('state',{code:saved});render();}catch{localStorage.removeItem('mafiaRoom');home();}}else home();setInterval(poll,2500);setInterval(clock,250);}catch(e){$('entry').innerHTML='<p>'+esc(e.message)+'</p><button onclick="location.reload()">Повторить</button>';}}
 boot();
})(window);
