-- AliveProject — Effect Engine foundation
begin;

alter table public.character_pool
  add column if not exists effect_key text,
  add column if not exists effect_params jsonb not null default '{}'::jsonb,
  add column if not exists target_kind text;

alter table public.player_cards
  add column if not exists effect_key text,
  add column if not exists effect_params jsonb not null default '{}'::jsonb,
  add column if not exists target_kind text;

alter table public.preset_character_traits
  add column if not exists effect_key text,
  add column if not exists effect_params jsonb not null default '{}'::jsonb,
  add column if not exists target_kind text;

create table if not exists public.round_effects (
  id bigint generated by default as identity primary key,
  room_code text not null,
  round integer not null,
  effect_key text not null,
  source_player_id text,
  target_player_id text,
  target_property_id text,
  effect_params jsonb not null default '{}'::jsonb,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists idx_round_effects_room_round
  on public.round_effects(room_code, round);
create index if not exists idx_round_effects_target
  on public.round_effects(target_player_id);
create index if not exists idx_round_effects_key
  on public.round_effects(effect_key);

-- Copy effect metadata into already-created player cards when possible.
update public.player_cards pc
set effect_key = cp.effect_key,
    effect_params = coalesce(cp.effect_params, '{}'::jsonb),
    target_kind = cp.target_kind
from public.character_pool cp
where pc.pool_id = cp.id
  and pc.category = 'special_condition'
  and (pc.effect_key is null or pc.target_kind is null);

-- Fix the two known target-type data errors from the previous audit.
update public.character_pool
set target_type = 'one'
where id = 1630;

update public.character_pool
set target_type = 'self'
where id = 1672;

-- Known vote effects from the existing project audit.
update public.character_pool
set effect_key = 'vote_nullified', target_kind = 'player'
where id = 1630;

commit;
