-- 0021_card_effects.sql
-- AliveProject / Этап 2
-- Реальные взаимодействия спецусловий группы card_effect.

begin;

alter table public.character_pool
  add column if not exists effect_key text,
  add column if not exists effect_params jsonb not null default '{}'::jsonb,
  add column if not exists target_kind text not null default 'player';

alter table public.preset_character_traits
  add column if not exists effect_key text,
  add column if not exists effect_params jsonb not null default '{}'::jsonb,
  add column if not exists target_kind text not null default 'player';

alter table public.player_cards
  add column if not exists effect_key text,
  add column if not exists effect_params jsonb not null default '{}'::jsonb,
  add column if not exists target_kind text not null default 'player';

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'character_pool_target_kind_check'
  ) then
    alter table public.character_pool
      add constraint character_pool_target_kind_check
      check (target_kind in ('player','property','room'));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'preset_character_traits_target_kind_check'
  ) then
    alter table public.preset_character_traits
      add constraint preset_character_traits_target_kind_check
      check (target_kind in ('player','property','room'));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'player_cards_target_kind_check'
  ) then
    alter table public.player_cards
      add constraint player_cards_target_kind_check
      check (target_kind in ('player','property','room'));
  end if;
end $$;

-- Таблица активных эффектов раунда.
create table if not exists public.round_effects (
  id bigint generated by default as identity primary key,
  room_code text not null,
  round integer not null,
  effect_key text not null,
  source_player_id text,
  target_player_id text,
  target_property_id bigint,
  effect_params jsonb not null default '{}'::jsonb,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists idx_round_effects_room_round
  on public.round_effects(room_code, round, is_active);

create index if not exists idx_round_effects_target
  on public.round_effects(room_code, target_player_id, is_active);

-- Разметка первой группы card_effect.
-- Важно: миграция не пытается угадать все 100 карт.
-- Она активирует только однозначные названия/формулировки.
update public.character_pool
set
  effect_key = case
    when text ilike '%ограблен%' or text ilike '%ограбление%' then 'steal_trait'
    when text ilike '%обмен%' and text ilike '%характер%' then 'swap_trait'
    when text ilike '%копир%' and text ilike '%характер%' then 'copy_trait'
    when text ilike '%наследств%' and text ilike '%характер%' then 'inherit_trait'
    when text ilike '%блокиров%' and text ilike '%багаж%' then 'block_luggage'
    else effect_key
  end,
  target_kind = case
    when text ilike '%бункер%' or text ilike '%свойство бункера%' then 'property'
    else target_kind
  end
where category = 'special_condition'
  and (
    text ilike '%ограблен%' or text ilike '%ограбление%'
    or (text ilike '%обмен%' and text ilike '%характер%')
    or (text ilike '%копир%' and text ilike '%характер%')
    or (text ilike '%наследств%' and text ilike '%характер%')
    or (text ilike '%блокиров%' and text ilike '%багаж%')
  );

update public.preset_character_traits
set
  effect_key = case
    when text ilike '%ограблен%' or text ilike '%ограбление%' then 'steal_trait'
    when text ilike '%обмен%' and text ilike '%характер%' then 'swap_trait'
    when text ilike '%копир%' and text ilike '%характер%' then 'copy_trait'
    when text ilike '%наследств%' and text ilike '%характер%' then 'inherit_trait'
    when text ilike '%блокиров%' and text ilike '%багаж%' then 'block_luggage'
    else effect_key
  end
where category = 'special_condition';

-- Переносим effect_key в уже существующие карточки игроков.
update public.player_cards pc
set
  effect_key = cp.effect_key,
  effect_params = coalesce(cp.effect_params, '{}'::jsonb),
  target_kind = coalesce(cp.target_kind, 'player')
from public.character_pool cp
where pc.pool_id = cp.id
  and pc.category = 'special_condition'
  and cp.effect_key is not null;

-- Для пресетных карточек pool_id может быть NULL.
update public.player_cards pc
set
  effect_key = pct.effect_key,
  effect_params = coalesce(pct.effect_params, '{}'::jsonb),
  target_kind = coalesce(pct.target_kind, 'player')
from public.preset_character_traits pct
where pc.pool_id is null
  and pc.category = 'special_condition'
  and pc.text = pct.text
  and pct.effect_key is not null;

-- Безопасный просмотр того, что реально разметилось.
-- SELECT id, text, effect_key, target_type, target_kind
-- FROM public.character_pool
-- WHERE category='special_condition'
-- ORDER BY id;

commit;
